version: "3.3"

services:
  traefik:
    image: traefik:1.4
    ports:
      - 80:80
      - 8080:8080
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.toml
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "3000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - traefik-net

  utm-service:
    container_name: utm-service
    build:
      context: ./utm-service/utm-service
      dockerfile: ./Dockerfile
    image: 127.0.0.1:5000/utm-service

  manager:
    container_name: manager
    build:
      context: ./DroneManager.API/DroneManager.API/
      dockerfile: ./Dockerfile
    image: 127.0.0.1:5000/manager
    environment:
      - ConnectionStrings__AppDbContext="Host=database;Port=5432;Username=madsfalken;Password=2cool4school;Database=healthydrone;"
    networks:
      - traefik-net
      - database-net
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.port=5000"
        - "traefik.backend=manager"
        - "traefik.frontend.rule=Path:/manager"
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./database/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "madsfalken"
      POSTGRES_PASSWORD: "2cool4school"
      POSTGRES_DB: "healthydrone"
    networks:
      - database-net

volumes:
  db_volume:

networks:
  traefik-net:
    driver: overlay
  database-net:

configs:
  traefik-config:
    file: config.toml