version: '3'
services:
    envoy:
        build: ./envoy
        ports:
            - "9902:9902"
            - "11000:11000"
        links:
            - mavsdk_server
    mavsdk_server:
        build: ./mavsdk_server
        ports:
            - "50052:50051"
            - "14545:14540/udp"
    #gazebo_sitl_headless:
     #   image: jonasvautherin/px4-gazebo-headless:v1.9.2
      #  environment:
       #     - NO_PXH=1
        #links:
         #   - mavsdk_server