// <auto-generated />
using System;
using LandingPoints.API.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace LandingPoints.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("LandingPoints.API.Domain.LandingPointsAPI.Domain.Models.LandingPoint", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("callsign")
                        .IsRequired()
                        .HasColumnType("character varying(10)")
                        .HasMaxLength(10);

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("type")
                        .HasColumnType("smallint");

                    b.HasKey("id");

                    b.ToTable("Landing Points");

                    b.HasData(
                        new
                        {
                            id = new Guid("57decbbe-668f-499e-afc8-1adb9b6b51d4"),
                            address = "J. B. Winsløws Vej 4, 5000 Odense",
                            callsign = "OUH-1",
                            description = "A hospital",
                            latitude = 55.059750000000001,
                            longitude = 10.606870000000001,
                            name = "Odense Universitets Hospital",
                            type = (byte)1
                        },
                        new
                        {
                            id = new Guid("fe04250f-a80a-4540-ba54-1b7e68832956"),
                            address = "Baagøes Alle 31, 5700 Svendborg",
                            callsign = "OUH-2",
                            description = "A hospital",
                            latitude = 55.385390999999998,
                            longitude = 10.366899999999999,
                            name = "Svendborg Sygehus (OUH)",
                            type = (byte)1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
